services:
  qbittorrent:
    container_name: qbittorrentwg
    image: ghcr.io/hotio/qbittorrent:release-5.0.4@sha256:d97080a8a978d7705297dc44bcd6c599b3b47631fec8dcfc0cb7039279d05b02
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Athens
      - WEBUI_PORTS=8880/tcp,8880/udp
      - VPN_ENABLED=false # Change this to false if you want to test that the app works.
      - VPN_CONF=wg0 # Place wg0.conf in ~/umbrel/app-data/data/config/wireguard/ - Dir gets created once you launch the app(it won't load because VPN_ENABLED=true and there's no wg0.conf).
      - VPN_PROVIDER=generic #
      - VPN_LAN_NETWORK=192.168.1.0/24 #
      - VPN_LAN_LEAK_ENABLED=true
      - VPN_EXPOSE_PORTS_ON_LAN #
      - VPN_AUTO_PORT_FORWARD=false #
      - VPN_AUTO_PORT_FORWARD_TO_PORTS= #
      - VPN_KEEP_LOCAL_DNS=false #
      - VPN_FIREWALL_TYPE=auto #
      - VPN_HEALTHCHECK_ENABLED=false
      - PRIVOXY_ENABLED=false
      - UNBOUND_ENABLED=false #
    volumes:
      - /home/umbrel/umbrel/app-data/sl1ng-qbittorrent/data/config:/config
      - /home/umbrel/umbrel/home/Downloads:/downloads
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1 #
      - net.ipv6.conf.all.disable_ipv6=1 #
    devices:
      - /dev/net/tun:/dev/net/tun # OPTIONAL, READ THIS
    restart: on-failure
#    network: "container:gluetun"
